application: 1heartpy
version: 5
runtime: python
api_version: 1

default_expiration: "15d"
#for browser static caching

#########################
handlers:

- url: /
  script: handlers/main.py

- url: /resources
  script: handlers/main.py

- url: /instructions
  script: handlers/main.py

- url: /wth
  script: handlers/main.py

- url: /badges
  script: handlers/badges.py

- url: /download
  script: handlers/zipme.py

- url: /shell
  script: handlers/shell.py
  login: required
  auth_fail_action: redirect

- url: /hangouts
  script: handlers/shell.py

- url: /shell.do
  script: handlers/shell.py
  login: required
  auth_fail_action: unauthorized

- url: /shell.delete
  script: handlers/shell.py

- url: /(.+\.(txt|xml|html))
  static_files: txt/\1
  upload: txt/(.+\.(txt|xml|html))
  expiration: "15d"
  
- url: /(.+\.(appcache))
  static_files: appcache/\1
  mime_type: text/cache-manifest
  upload: appcache/(.+\.(appcache))
  expiration: "15d"
  
- url: /(.+\.(gif|png|jpg|ico|jpeg))
  static_files: site/images/\1
  upload: site/images/(.+\.(gif|png|jpg|ico|jpeg))
  expiration: "30d"

- url: /css
  static_dir: site/css
  expiration: "30d"

- url: /js
  static_dir: site/js
  expiration: "30d"

- url: /images
  static_dir: site/images
  expiration: "30d"
  
- url: /.*
  script: handlers/main.py

#########################
builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on

#########################
inbound_services:
  - warmup

#########################
error_handlers:
  - file: error/error.html

  - error_code: over_quota
    file: error/quota.html

  - error_code: dos_api_denial
    file: error/deny.html

  - error_code: timeout
    file: error/timeout.html

#########################
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak
