application: 1heartpy
version: 2a
runtime: python
api_version: 1

default_expiration: "15d"
#for browser static caching

#########################
handlers:

- url: /
  script: handlers/main.py
  secure: always

- url: /resources
  script: handlers/main.py
  secure: always

- url: /instructions
  script: handlers/main.py
  secure: always

- url: /wth
  script: handlers/main.py
  secure: always

- url: /download
  script: handlers/zipme.py
  secure: always

- url: /shell
  script: handlers/shell.py
  login: admin
  secure: always
  auth_fail_action: redirect

- url: /shell.do
  script: handlers/shell.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url: /(.+\.(txt|xml|html))
  static_files: txt/\1
  upload: txt/(.+\.(txt|xml|html))
  expiration: "15d"
  
- url: /(.+\.(appcache))
  static_files: appcache/\1
  mime_type: text/cache-manifest
  upload: appcache/(.+\.(appcache))
  expiration: "15d"
  

- url: /(.+\.(gif|png|jpg|ico|jpeg))
  static_files: site/images/\1
  upload: site/images/(.+\.(gif|png|jpg|ico|jpeg))
  expiration: "30d"

- url: /css
  static_dir: site/css
  expiration: "30d"

- url: /js
  static_dir: site/js
  expiration: "30d"

- url: /images
  static_dir: site/images
  expiration: "30d"

- url: /stats
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin
  secure: always
  auth_fail_action: redirect

- url: /_ah/admin
  script: $PYTHON_LIB/google/appengine/ext/admin  
  login: admin
  secure: always
  auth_fail_action: redirect

- url: /connector
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url: /data
  script: $PYTHON_LIB/google/appengine/ext/datastore_admin
  login: admin
  secure: always
  auth_fail_action: redirect

- url: /_ah/mail/.+ 
  script: handlers/email.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/message/chat/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/subscription/subscribe/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/subscription/subscribed/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/subscription/unsubscribe/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/subscription/unsubscribed/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/presence/available/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/presence/unavailable/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/xmpp/presence/probe/
  script: handlers/chat.py
  login: admin
  secure: always
  auth_fail_action: unauthorized

- url:  /_ah/warmup/
  script: handlers/ping.py
  login: admin
  secure: always
  auth_fail_action: unauthorized
  
- url: /.*
  script: handlers/main.py
  secure: always

#########################
builtins:
- datastore_admin: on
- appstats: on
- remote_api: on
- admin_redirect: on

#########################
inbound_services:
  - warmup
  - mail
  - xmpp_message
  - xmpp_presence
  - xmpp_subscribe


#########################
error_handlers:
  - file: error/error.html

  - error_code: over_quota
    file: error/quota.html

  - error_code: dos_api_denial
    file: error/deny.html

  - error_code: timeout
    file: error/timeout.html

#########################
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak
